/* barrel: the single import surface for the ported + new tier-2 components.
   visual styling lives in src/index.css (token-driven classes) — import that once at
   the app / storybook root; these components only emit the matching class names. */
export { default as Button, ButtonGroup, Segmented } from './Button.jsx'
export { default as Input, Textarea, Select, Field } from './Input.jsx'
export { default as Checkbox, Radio, RadioGroup } from './Checkbox.jsx'
export { default as Switch } from './Switch.jsx'
export { default as Chip, FilterChip, StatusDot, CountBadge } from './Chip.jsx'
export { default as Card, CardImg, Row, MetaItem } from './Card.jsx'
export { default as Tabs } from './Tabs.jsx'
export { default as Breadcrumb, Steps } from './Breadcrumb.jsx'
export { default as Pager } from './Pager.jsx'
export { default as Pagination } from './Pagination.jsx'
export { default as Menu } from './Menu.jsx'
export { default as Tooltip, Popover } from './Tooltip.jsx'
export { Avatar, AvatarGroup, Kbd, KbdChord, Tag } from './Avatar.jsx'
export { default as BrandMark, resolveBrand } from './BrandMark.jsx'
export { default as EmptyState } from './EmptyState.jsx'
export { Skeleton, Progress, Spinner, Toast, FeedbackPanel } from './Feedback.jsx'
export { default as DataTable } from './DataTable.jsx'
export { default as ChartBar } from './ChartBar.jsx'
export { default as ChartLine } from './ChartLine.jsx'
export { default as Sparkline } from './Sparkline.jsx'
export { default as Accordion } from './Accordion.jsx'
export { default as Timeline, TimelineItem, ToolCall, ThinkingBlock } from './Timeline.jsx'
export { default as ToastProvider, useToast } from './ToastHost.jsx'
export { default as DateRange, DateRangeCalendar, formatRange, DATE_PRESETS } from './DateRange.jsx'
export { default as Dialog } from './Dialog.jsx'
export { default as CommandPalette } from './CommandPalette.jsx'
/* tier-3 "in use" composites (peasant app families). these ship their OWN colocated css file
   (imported by the component), not src/index.css, so they stay self-contained; the styling still
   reads only system tokens. */
export { default as MapNode, IntensitySwatch, RampLegend, Heatmap, IntensityScope, coverageLevel, effortLevel, locSize } from './Intensity.jsx'
export { default as Treemap, squarify } from './Treemap.jsx'
export { default as CommitGraph } from './CommitGraph.jsx'
export { default as DiffView } from './DiffView.jsx'
export { default as StepWizard, StepIndicator } from './StepWizard.jsx'
export { default as TimeStrip } from './TimeStrip.jsx'
export { default as Explainer, Term } from './Explainer.jsx'
export { default as RedactionReview, WhereDoesThisGo } from './Redaction.jsx'
/* tier-3, second pass: the governance / map / viewer / onboarding families that complete the set
   needed to rebuild peasant + village from scratch. all colocated-css, tokens-only. */
export { default as ConsentDialog, ConsentSummary } from './ConsentDialog.jsx'
export { default as PolicySelect } from './PolicySelect.jsx'
export { default as ModerationQueue, ApprovalBar } from './ModerationQueue.jsx'
export { default as RoleRoster, ConfirmInline, DangerZone } from './RoleRoster.jsx'
export { default as MapCanvas } from './MapCanvas.jsx'
export { default as RailShell, RailSection, SplitRail } from './RailShell.jsx'
export { default as ProviderIcon, ProviderTag, ProviderName, AccentLegend, PROVIDER_ACCENT } from './ProviderIcon.jsx'
export { default as StepsWaterfall } from './StepsWaterfall.jsx'
export { default as GroupedMultiSelect } from './GroupedMultiSelect.jsx'
export { default as EvidenceCaption, EvidenceTarget } from './EvidenceCaption.jsx'
export { PhaseDivider, Phase, TaskBoundary, CheckpointMarker, TurnContextBar } from './TranscriptMarkers.jsx'
export { default as ToolCallRenderer } from './ToolRenderers.jsx' // distinct from Timeline's ToolCall
export { default as Tour } from './Tour.jsx'
export { default as ConnectionPill, DataState, TeachingEmptyState } from './ConnectionState.jsx'
export { default as SignInProviders, HandleClaim, OnboardingCard } from './SignIn.jsx'
export { default as CliSteps, CommandBlock, GettingStarted } from './CliOnboard.jsx'
export { default as FacetRail } from './FacetRail.jsx'
export { StatTile, StatGrid, GovTile, ProviderBars } from './StatTiles.jsx'
export { default as VisibilitySegmented, VisibilityEye, ScopeChip, FocusedModeToggle } from './VisibilityControl.jsx'
